services:
  postgres:
    image: postgres:16
    container_name: ur-postgres
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio:
    image: minio/minio:latest
    container_name: ur-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mlflow:
    build:
      context: ./apps/mlflow
    container_name: ur-mlflow
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      MLFLOW_ARTIFACT_ROOT: ${MLFLOW_ARTIFACT_ROOT}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_DEFAULT_REGION: us-east-1
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --artifacts-destination ${MLFLOW_ARTIFACT_ROOT}
      --allowed-hosts mlflow,mlflow:5000,localhost,localhost:5051,127.0.0.1,127.0.0.1:5051
      --cors-allowed-origins *
    ports:
      - "${MLFLOW_PORT:-5051}:5000"

  pipeline:
    build:
      context: ./apps/pipeline
      dockerfile: Dockerfile
    container_name: ur-pipeline
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATA_DIR: /data
      BUCKET_MIN: ${BUCKET_MIN}
      DELTA_THRESHOLD_MIN: ${DELTA_THRESHOLD_MIN}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_EXPERIMENT: ${MLFLOW_EXPERIMENT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
    command: >
      sh -lc "
      mc alias set urminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p urminio/mlflow || true &&
      python run.py
      "


  api:
    build:
      context: ./apps/api
    container_name: ur-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${API_PORT:-8000}:8000"

  grafana:
    image: grafana/grafana:latest
    container_name: ur-grafana
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  pg_data:
  minio_data:
  grafana_data:
