apiVersion: 1
datasources:
  - name: Postgres-UR
    type: postgres
    access: proxy
    url: postgres:5432
    database: urmvp
    user: urmvp
    secureJsonData:
      password: urmvp
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
    isDefault: true
